#! /usr/bin/env python3

import pandas as pd
import json
import sys

if len(sys.argv) < 2:
    print("Pass the location of the population.csv as first argument.")
    exit()


POP_YEAR=2018

with open("data/european-countries.json") as f:
    europe_data = f.read()

europe = json.loads(europe_data)

population = pd.read_csv(sys.argv[1])

pop_outdata = dict()

for i, row in population.iterrows():
    cc = row["Country Code"]
    if cc in europe and row["Year"] == POP_YEAR:
        if not cc in pop_outdata:
            pop_outdata[cc] = dict()
        pop_outdata[cc][row["Year"]] = row["Value"]

elm_header = """module Data exposing
    ( europeanCountries
    , population
    )

-- This module is autogenerated! Look at prebuild.py for changing the content.

import Dict


"""

with open("src/Data.elm", "w") as f:
    f.write(elm_header)
    countries_list = list()
    for c in europe:
        countries_list.append(f"\"{c}\"")
    f.write("europeanCountries =\n    [ " + ", ".join(countries_list) + " ]")
    f.write("\n\n\n")
    f.write("population =\n")
    f.write("    Dict.fromList [ ")
    pop_list = list()
    for k, v in pop_outdata.items():
        pop_list.append("( \"{cc}\", Dict.fromList [ ( {year}, {pop} ) ] )".format(
                cc = k,
                year = POP_YEAR,
                pop = v[POP_YEAR]
            ))
    f.write(", ".join(pop_list) + " ]\n")



