module Data exposing
    ( europeanCountries
    , population
    )

-- This module is autogenerated! Look at prebuild.py for changing the content.

import Dict


europeanCountries =
    [ "ESP", "IRL", "FIN", "HUN", "GRC", "MLT", "SVN", "HRV", "BEL", "CYP", "AUT", "EST", "LVA", "ROU", "SVK", "DEU", "LUX", "FRA", "DNK", "PRT", "SWE", "POL", "NLT", "BGR", "CZE", "ITA", "LTU" ]


population =
    Dict.fromList [ ( "AUT", Dict.fromList [ ( 2018, 8840521 ) ] ), ( "BEL", Dict.fromList [ ( 2018, 11433256 ) ] ), ( "BGR", Dict.fromList [ ( 2018, 7025037 ) ] ), ( "HRV", Dict.fromList [ ( 2018, 4087843 ) ] ), ( "CYP", Dict.fromList [ ( 2018, 1189265 ) ] ), ( "CZE", Dict.fromList [ ( 2018, 10629928 ) ] ), ( "DNK", Dict.fromList [ ( 2018, 5793636 ) ] ), ( "EST", Dict.fromList [ ( 2018, 1321977 ) ] ), ( "FIN", Dict.fromList [ ( 2018, 5515525 ) ] ), ( "FRA", Dict.fromList [ ( 2018, 66977107 ) ] ), ( "DEU", Dict.fromList [ ( 2018, 82905782 ) ] ), ( "GRC", Dict.fromList [ ( 2018, 10731726 ) ] ), ( "HUN", Dict.fromList [ ( 2018, 9775564 ) ] ), ( "IRL", Dict.fromList [ ( 2018, 4867309 ) ] ), ( "ITA", Dict.fromList [ ( 2018, 60421760 ) ] ), ( "LVA", Dict.fromList [ ( 2018, 1927174 ) ] ), ( "LTU", Dict.fromList [ ( 2018, 2801543 ) ] ), ( "LUX", Dict.fromList [ ( 2018, 607950 ) ] ), ( "MLT", Dict.fromList [ ( 2018, 484630 ) ] ), ( "POL", Dict.fromList [ ( 2018, 37974750 ) ] ), ( "PRT", Dict.fromList [ ( 2018, 10283822 ) ] ), ( "ROU", Dict.fromList [ ( 2018, 19466145 ) ] ), ( "SVK", Dict.fromList [ ( 2018, 5446771 ) ] ), ( "SVN", Dict.fromList [ ( 2018, 2073894 ) ] ), ( "ESP", Dict.fromList [ ( 2018, 46796540 ) ] ), ( "SWE", Dict.fromList [ ( 2018, 10175214 ) ] ) ]
